# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('photo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_N', models.IntegerField()),
                ('asset_no', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=1000)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('present', models.BooleanField(default=True)),
                ('map_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=10)),
                ('staff_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostiarius.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('asset_no', models.CharField(max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostiarius.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostiarius.Item'),
        ),
    ]
