# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('photo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=1000)),
                ('present', models.BooleanField(default=True)),
                ('photo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('returnDate', models.DateField(default=None)),
                ('asset_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostiarius.Item')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostiarius.Item'),
        ),
    ]
