# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostiarius', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='present',
            field=models.BooleanField(default=True),
        ),
    ]
