# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostiarius', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='return_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
