# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostiarius', '0002_item_maintenance_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
