# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostiarius', '0002_auto_20170705_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='returnDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
